.ALIASES
V_V             V(+=N00067 -=0 ) CN @EXP 1.SCHEMATIC1(sch_1):INS26@SOURCE.VDC.Normal(chips)
R_R             R(1=0 2=N00067 ) CN @EXP 1.SCHEMATIC1(sch_1):INS51@ANALOG.R.Normal(chips)
R_R2            R2(1=N00347 2=N00343 ) CN @EXP 1.SCHEMATIC1(sch_1):INS258@ANALOG.R.Normal(chips)
R_R3            R3(1=0 2=N00347 ) CN @EXP 1.SCHEMATIC1(sch_1):INS274@ANALOG.R.Normal(chips)
R_R1            R1(1=N00343 2=N00331 ) CN @EXP 1.SCHEMATIC1(sch_1):INS290@ANALOG.R.Normal(chips)
V_Vs            Vs(+=N00331 -=0 ) CN @EXP 1.SCHEMATIC1(sch_1):INS315@SOURCE.VDC.Normal(chips)
.ENDALIASES
